### ISSUE TITLE
@last_ping_request and @last_ping_response

### ISSUE THREAD

**Issue by crawler** [njh/ruby-mqtt#107]
Hi,
Found this issue when i was writing code that recovers broken MQTT connection.
Think that both @last_ping_request and @last_ping_response variables should be reset in #connect method, just before starting @read_thread

Here the code to reproduce it:

```
mqtt = MQTT::Client.new('mqtt://test.mosquitto.org')
sleep 24
mqtt.connect
mqtt.subscribe('#')

mqtt.get do |topic, payload| 
  puts topic, payload
end # => No Ping Response received for 23 seconds (MQTT::ProtocolException)
# In first keep_alive!

```

**Comment by ninp0** [comment]
To add to what @crawler is saying if you set:

```
mqtt.keep_alive = 0
```

It will immediately return from https://github.com/njh/ruby-mqtt/blob/b2e48d05f48919949c1c23f6fd5b9f05b6265a82/lib/mqtt/client.rb#L533 thus bypassing `@last_ping_request`  / `@last_ping_response` evaluation.

That said, then it pretty much immediately begins to raise this error:
https://github.com/njh/ruby-mqtt/blob/b2e48d05f48919949c1c23f6fd5b9f05b6265a82/lib/mqtt/packet.rb#L223

Here's the full stacktrace:

```
mqtt-0.6.0/lib/mqtt/packet.rb:223:in 'MQTT::Packet.read_byte': Failed to read byte from socket (MQTT::ProtocolException)
        from /usr/local/rvm/gems/ruby-3.4.1@global/gems/mqtt-0.6.0/lib/mqtt/packet.rb:30:in 'MQTT::Packet.read'
        from /usr/local/rvm/gems/ruby-3.4.1@global/gems/mqtt-0.6.0/lib/mqtt/client.rb:471:in 'MQTT::Client#receive_packet'
        from /usr/local/rvm/gems/ruby-3.4.1@global/gems/mqtt-0.6.0/lib/mqtt/client.rb:278:in 'block in MQTT::Client#connect'
```
