### ISSUE TITLE
Thread termination with exception not handled?

### ISSUE THREAD

**Issue by phlegx** [njh/ruby-mqtt#142]
With this simple implementation, I get an exception after broker goes down for some reason.

```
client.subscribe('test' => 0)
client.get do |topic, message|
  # Block is executed for every message received
end
````

Here the log:

```#<Thread:0x0000556201e78b10 /usr/local/bundle/bundler/gems/ruby-mqtt/lib/mqtt/client.rb:271 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/bundler/gems/ruby-mqtt/lib/mqtt/packet.rb:222:in `getbyte': Connection reset by peer @ io_fillbuf - fd:5 (Errno::ECONNRESET)
from /usr/local/bundle/bundler/gems/ruby-mqtt/lib/mqtt/packet.rb:222:in `read_byte'
from /usr/local/bundle/bundler/gems/ruby-mqtt/lib/mqtt/packet.rb:30:in `read'
from /usr/local/bundle/bundler/gems/ruby-mqtt/lib/mqtt/client.rb:466:in `receive_packet'
from /usr/local/bundle/bundler/gems/ruby-mqtt/lib/mqtt/client.rb:273:in `block in connect'
```
How can I rescue from this exception?

**Comment by JakubSzajna** [comment]
Hello!
I just run into that issue too. It's due to a fact that Exception [here](https://github.com/njh/ruby-mqtt/blob/main/lib/mqtt/client.rb#L476) is in fact `MQTT::Exception` instead of `::Exception` and I wonder if this is intentionally implemented that way? Because of that, if the connection is broken for some reason [the thread](https://github.com/njh/ruby-mqtt/blob/main/lib/mqtt/client.rb#L276) dies silently and the only trace of that is in the logs.

I don't want to globally set `abort_on_exception`, but if using `MQTT::Exception` is intentional, maybe allowing one to set this value for the `@read_thread` specifically via some config option + having the issue described somewhere would be enough?

My fix for now is something like this:

```
MQTT::Client.prepend(Module.new do
  def receive_packet
    super
  rescue ::Exception => ex
    Thread.current[:parent].raise(ex)
  end
end)
```

**Comment by phlegx** [comment]
@JakubSzajna but ruby-mqtt have this definition: [main/lib/mqtt.rb#L23](https://github.com/njh/ruby-mqtt/blob/main/lib/mqtt.rb#L23)
```ruby
module MQTT
  ...
  # Super-class for other MQTT related exceptions
  class Exception < ::Exception
  end
  ...
end

**Comment by JakubSzajna** [comment]
Yes, it does have this definition and it branches out from stdlib `Exception`.

`rescue Exception => exp` in `MQTT` module refers to `MQTT::Exception` instead of `::Exception` though.
 So it would catch exceptions like `MQTT::Exception` and everything that inherits from `MQTT::Exception`.
`Errno::ECONNRESET` does not have `MQTT::Exception` in it's ancestors chain, so it won't be catched in the rescue clause you mentioned.

The monkey-patch from my message wraps the whole `receive_packet` in the rescue clause, so every exception that will be raised inside `receive_packet` will be catched there and elevated to the parent thread. Hope this is the answer for your question :) It is supposed to make sure the exception from your initial message (and others from inside the `receive_packet` method) can be rescued. So this does not actually rescue from the exception, it just makes it `rescue`'able :) To catch this exception, use a rescue clause in a scope where you use `MQTT::Client.connect` method.

**Comment by phlegx** [comment]
@JakubSzajna can you write a PR please?

**Comment by phlegx** [comment]
Found similar PR #112 related to StandardError.

**Comment by JakubSzajna** [comment]
I don't think this fixes the issue were talking about here. If I find some time, I'll create a PR to include a proposed solution in the gems code.

**Comment by Toucouleur66** [comment]
> I don't think this fixes the issue were talking about here. If I find some time, I'll create a PR to include a proposed solution in the gems code.

any hope for this PR?
